package com.amine.amineapp.dao;

public class Queries {
    public static final String RELEVE_DE_SOLDE = "SELECT ACOWNERID MANDANT, B.BPNAME LIBELLEMANDANT, CASE WHEN C.POAHOLDER IS NULL THEN A.ACOWNERID ELSE C.POAHOLDER END AS MANDATAIRE, CASE WHEN D.BPNAME IS NULL THEN B.BPNAME ELSE D.BPNAME END AS LIBELLEMANDATAIRE, A.ACNO, A.SECURITYID, E.ENGLONGNAME, E.INSTRCTGRY, A.NORMALQUANTITY FROM STG_BKP_SECPOSEOD A LEFT JOIN STG_BPM_POADETAILS C ON A.ACOWNERID = C.BPID LEFT JOIN STG_BPM_PRMRYDTLS D ON C.POAHOLDER = D.BPID, STG_BPM_PRMRYDTLS B, STG_FIM_PRMYDTLS E WHERE A.ACOWNERID = B.BPID AND A.SECURITYID = E.INSTRID AND A.NORMALQUANTITY != 0 AND %s ORDER BY A.ACOWNERID";
}
